<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="fr"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="fr"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="fr"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="fr"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="" lang="fr"> <!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title ?></title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</head>

<body>
    <a name="top"></a>
    <?php echo $content; ?>
</body>
</html>